### ISSUE TITLE
Complaint Roll Up

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#103]
I finally was able to run a side by side of the two files... It appears there is another issue with the complaint roll up.

11908103,UNIVERSITY OF ARIZONA

While there are no complaints about this facility code, there are complaints about the OPE-6 (001083) school level.

I have two complaints for the total roll up in my database, but no complaints are appearing in the data service export.

![image](https://cloud.githubusercontent.com/assets/4397508/15789392/eafa4520-2999-11e6-994b-e5aad8880b3a.png)

**Comment by mphprogrammer** [comment]
Weird - I show one complaint entry with Accreditation, Financial Issues ... in the complaints csv:

![screen shot 2016-06-06 at 12 34 56 pm](https://cloud.githubusercontent.com/assets/4104431/15829747/1c6cff58-2be3-11e6-935b-a1f4bcfd94a1.png)

The data.csv outputs
![screen shot 2016-06-06 at 12 43 36 pm](https://cloud.githubusercontent.com/assets/4104431/15830025/5aa4bbf2-2be4-11e6-93ad-b9baa11088d9.png)

Although having "other" complaints set to 1 looks like a bug.

**Comment by saintsoup52** [comment]
My issue is not with the complaints for a particular school but rather the roll up complaint column.

See this shouldn't be possible... the "2" should be in all three complaint roll up columns.

![image](https://cloud.githubusercontent.com/assets/4397508/15831839/83e29b70-2bed-11e6-8f74-1b68bc559d6b.png)

**Comment by saintsoup52** [comment]
This issue is happening in a number of other places too:
319D3132,POLYTECHNIC INSTITUTE OF NEW YORK UNIVERSITY

**Comment by mphprogrammer** [comment]
With your example, If I cannot use the complaints ope and the complaint has no facility code how do I roll up?

**Comment by mphprogrammer** [comment]
![screen shot 2016-06-07 at 12 24 22 pm](https://cloud.githubusercontent.com/assets/4104431/15865988/f540593e-2caa-11e6-8ea7-a9104855a0e7.png)

"We have no way to update the OPE IDs in the complaint database so the longer we go the worse that list will get."

If a school has no facility_code and I cannot use the ope, then how do I "roll-up" the complaint to the ope?

**Comment by saintsoup52** [comment]
You can't... My complaint file has facility codes for those I am reporting.

For some reason the complaint file keeps reverting to the old file you are using.

**Comment by mphprogrammer** [comment]
Could you send me your complaint file?

**Comment by saintsoup52** [comment]
I uploaded it into the data service otherwise I can send this evening

**Comment by mphprogrammer** [comment]
Should be good. Thanks, but I’ll let you know if there is an issue with it.
