### ISSUE TITLE
Multiple Settlement Caution Flags not showing up

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#128]
This is an issue with us adding the 700+ new caution flags for schools... This is a new we have not had before.

If a school like Brown Mackie College-Akron (unitID 205647) appears twice in the settlement csv only one of the settlement description appears on the tool.

![image](https://cloud.githubusercontent.com/assets/4397508/16687162/d78195be-44e4-11e6-88e4-ef5b797634b0.png)

So in the example above (FC 21974535) should have two caution flag reasons "Settlement with U.S. Government" & "Accreditor under review"

However now in the data service it appears only with "Accreditor under review".

Because Heightened Cash Monitoring is merged from another file that appears regardless.

**Comment by koconnor719** [comment]
thanks for identifying this so fast!

**Comment by mphprogrammer** [comment]
@saintsoup52  - can you send me that CSV - my settlements file only has one row for Brown Mackie, and I'll need it to test.

**Comment by saintsoup52** [comment]
I just uploaded it to DS… here it is again.

Patrick Campbell
o) 202-435-7299

Confidentiality Notice: If you received this email by mistake, you should notify the sender of the mistake and delete the email and any attachments. An inadvertent disclosure is not intended to waive any privileges.
