### ISSUE TITLE
Tool Tips missing information

### ISSUE THREAD

**Issue by ericks24** [department-of-veterans-affairs/gibct-data-service#131]
All Tool Tips pop ups are displaying half information on Comparision Tool. Attached is a screen shot of the issue. The scroll bar on the right side is grayed out so user can't scroll down to view additional information. 
![tool tips](https://cloud.githubusercontent.com/assets/15673554/16996357/fa495ffc-4e7e-11e6-8451-7e8e679e1ee6.png)

**Comment by ayaleloehr** [comment]
I believe this will be fixed in our release tomorrow. Will check back then to make sure that's true.

**Comment by ayaleloehr** [comment]
@ericks24 is this better now or does the same issue happen still?

**Comment by ericks24** [comment]
everything looks good now. thanks for making change
