### ISSUE TITLE
Crosswalk and Apostrophes 

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#133]
We need to find a replace for apostrophes in the crosswalk. @mphprogrammer you have any suggestions?

Background:
OPE IDS usually start with a zero and those zeroes  get lost when the data is switched to an excel file. So originally we used quotation marks to preserve the leading zeroes.  "00736204"

When we moved to the data service we stop using quotation marks because it was breaking the csv files @mphprogrammer can explain more. 

However now that we switched to apostrophes ('00736204'), excel is not recognizing the leading apostrophe because it signals a formatting issue, which means it impossible to update the crosswalk in excel with apostrophes.

http://www.pcreview.co.uk/threads/leading-apostrophe-appears-in-the-formula-bar-but-not-in-the-cells.3664427/

**Comment by saintsoup52** [comment]
So I just did a test...  if you try to update the OPE ID with a single apostrophe excel strips it before it uploaded in the data service. 

This is not good because this breaks the crosswalk for OPE IDs.

If you add two apostrophes the first one disappears and the second goes through, but this is hard to remember and will done wrong. :-/

**Comment by mphprogrammer** [comment]
@saintsoup52 Unless you need the leading 0's in the crosswalk CSV for your own purposes, you need not enclose the opes in quotes at all. The DS automatically left pads opes with 0s to 8 places.

**Comment by saintsoup52** [comment]
We need to have it for the data dashboards... excel is not that smart

**Comment by mphprogrammer** [comment]
I just tried loading with double quotes, there shouldn't be an issue if the double quotes are not part of the text like "the embedded "double quotes" cause issues with csv.read". At least as far as OPEs are concerned.

**Comment by mphprogrammer** [comment]
Give it a shot an let me know.

**Comment by saintsoup52** [comment]
This works!! Hooray!
