### ISSUE TITLE
Addressing data integrity

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gibct-data-service#134]
Do we have a process in place to address issues dealing with the correctness of data? For example, if a school is listed as "Private" in Weams, but should be listed as "For Profit", how is that changed? I could create issues in the data service, but technically, that would not be the correct thing to do. @saintsoup52 @ayaleloehr @koconnor719  @ericks24 ?

**Comment by koconnor719** [comment]
i don't think we need a "for profit" type? private is the correct type so there is no data quality issue.

**Comment by mphprogrammer** [comment]
Closing the issue.

**Comment by saintsoup52** [comment]
There is most definitely a "for profit" type of school... I hope we are not changing that in anyway.

As for if there is a school wrongly labelled in WEAMS (e.g., the facility code has the wrong first digit), that needs be resolved by the ELR on the Education Service team and will be updated in the next monthly WEAMS upload.

**Comment by koconnor719** [comment]
we aren't changing anything.  marc pls. advise on a response to the user voice issue when you have a minute per patrick's message above. thanks.
