### ISSUE TITLE
Upload CSV fails when CSV has unix-style line endings

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gibct-data-service#137]
Attempting to upload an otherwise-valid CSV that has unix-style line termination instead of DOS-style line termination causes the upload operation to fail with this error:

```
Errors prohibited this file from being saved:
undefined method `lines' for nil:NilClass
```

Workaround is to convert the file e.g. with the utility "unix2dos". But if any further development effort is allocated to this tool, it would be nice if it worked irrespective of line termination style.

**Comment by ben-USDS-damman** [comment]
(moved)
