### ISSUE TITLE
Devise sessions table looks like it grows without bound

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gibct-data-service#139]
While doing db migration from e/w to govcloud, was debugging a db restore and observed the following:

```
select count(*) from sessions;
 count
--------
 411715
```

It seems like devise never culls sessions from that table. Not sure if this is a matter of devise configuration or a bug.

We can clear that table with a rake:db command but we should also ensure this doesn't continue to happen.

**Comment by ben-USDS-damman** [comment]
@patrickvinograd I would imagine our half a dozen users rarely log out. Can we easily configure a `rake db:sessions:clear RAILS_ENV=production` cron job to run every weekend?

**Comment by patrickvinograd** [comment]
We are now up to:
```
select count(*) from sessions;
  count
---------
 1905709
(1 row)
```
so I kind of suspect that every get of a GIDS url results in a new entry in the sessions table?

**Comment by patrickvinograd** [comment]
E.g. the automated monitoring.

**Comment by ben-USDS-damman** [comment]
Perhaps pointing it to an API endpoint (no auth) would help in the future?

**Comment by patrickvinograd** [comment]
Yeah, right now all GIDS controllers are authenticated but once the API endpoints are available I'll point at that. Would like to keep this open to track verifying that we aren't still generating infinite session rows and also to track clearing the existing sessions.

**Comment by patrickvinograd** [comment]
If for any reason we decide we still need a cron job (I think we can live without it given we have less than 10 users) I'll set up `whenever` with a rake task. I know we use sidekiq in vets-api but that seems like overkill for this.

**Comment by ben-USDS-damman** [comment]
Closing this issue because it's tracked elsewhere
