### ISSUE TITLE
DB push operation should be implemented as HTTP POST, not GET

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gibct-data-service#141]
The DB push operation is currently factored as an HTTP GET operation. While it is nominally idempotent in that it should leave the database in the same state, it's really a complicated, potentially destructive, and long-running operation that should not be automatically re-tried by the system. 

When deployed in devops with 2 load-balanced instances, if you do a DB push and the reverse proxy times out on the initial instance, it retries the request (because it should be safe to retry GETs) on the second instance, and the two instances start racing each other, both pushing to the database. You wind up with duplicate records in the target database.

For now I will seek to avoid this problem by setting a much higher read timeout on the reverse proxy, but I strongly recommend the DB push operation be refactored to be an HTTP POST operation, which will not be auto-retried by the HTTP infrastructure.

**Comment by saneshark** [comment]
@mphprogrammer @ben-USDS-damman where are we with this one? Is this still relevant or can it be safely closed?
