### ISSUE TITLE
Enable rubocop, lint, any other relevant checks in Travis

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gibct-data-service#149]
Despite what the README says, Travis is not running rubocop or lint checks, and there are a bunch of ruby and javascript errors from those tools. Fix all issues, and enable those checks in Travis.

**Comment by saneshark** [comment]
@ayaleloehr this one two. There is an open PR that runs rubocop -a to update for the linting, I'm having @mphprogrammer review it before that gets merged, but linters should now be available.

**Comment by ayaleloehr** [comment]
I think this should be assigned to @ben-USDS-damman or @mphprogrammer to be sure that linters and rubocop is running. Not sure what other guidance I can provide here?  Once they're both running on PRs, then yes, should be good to close.

**Comment by ben-USDS-damman** [comment]
My recently-merged PR was run through `rake lint` and the rewrite-1 branch has no rubocop or scss-lint offenses.
