### ISSUE TITLE
Enable Travis CI for production branch

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gibct-data-service#151]
Latest production merge revealed that Travis CI is not enabled for PRs to the production branch. Github says it is waiting for them, but there's no indication of a job being run in the Travis UI.

**Comment by saneshark** [comment]
@ayaleloehr is it ok to close? I believe @knkski made the necessary changes yesterday.

**Comment by ayaleloehr** [comment]
That feels like a question for @knkski then... if he made the changes, then yes!
