### ISSUE TITLE
Implement simple preview functionality into GIDS

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gibct-data-service#160]
Current design of GIDS/GIBCT requires deploying a parallel copy of GIBCT as a "preview" version that stakeholders can use to verify that their data or parameter updates in GIDS look correct. GIDS users can push the new data to preview, verify it, then push it to production.

Once GIBCT is integrated with vets-api/vets-website, it will not be feasible to deploy a second copy of those applications just for the sake of GIBCT-preview functionality. 

Instead, some simplified GIBCT preview behavior should be integrated into GIDS itself. A replica of the GIBCT schema can be added to GIDS, and GIDS can push to the local database first, then push to production GIBCT once users are satisfied. The preview does not need to look identical to GIBCT, it just needs to present enough data and search capability that users can be confident that the data update is correct. It probably needs:
- Lookup single institution (by name or institution code?) with stripped down institution detail page
- Simple benefits estimator/search. 

See also https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/438 for further justification for this change.

**Comment by typesend** [comment]
Per our last meeting, data preview functionality is being implemented within the GI Bill react app of vets-website instead. (An optional url param will determine which version of the data to fetch.)

This issue can be closed but I don't have closing superpowers on this repo.
