### ISSUE TITLE
Use College Scorecard API

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/gibct-data-service#21]
Right now, the application loads a CSV from College Scorecard (from Department of Education). However, College Scorecard exposes an API and this data could be auto-loaded and updated. This is not done right now because of time constraints, but future dreams:
- Use the API instead of a CSV, wholly eliminating the manual labor of updating this data
- (Bigger, probably outside the scope of this Issue) Have the Dept of Ed own this tool, or incorporate its functionality into College Scorecard.

**Comment by rickleegit** [comment]
Closing this. We discussed the reasons why this was not possible at the moment following the creation of this issue. Perhaps in a future state, we will be able to achieve this.
