### ISSUE TITLE
Change routes for non-idempotent actions in dashboard

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gibct-data-service#213]
Currently, non-idempotent actions are mapped to get requests. This is not per HTTP specification. Change non-idempotent routes (build, push) in dash from GET to POST or PUT as appropriate.

**Comment by patrickvinograd** [comment]
I agree this can probably be deferred from the launch-blocking list, however it's not just an academic risk - there are various web accelerator plugins (not as popular as they used to) and even chrome itself has a prefetch function that pre-follows links as you browse. It will follow GETs but not PUTs/POSTs so could trigger an action in GIDS.

**Comment by leannammiller** [comment]
@patrickvinograd @mphprogrammer - sounds like this is something that should happen this sprint if we're trying to stop work on GIBCT after this sprint. Is this correct?

**Comment by patrickvinograd** [comment]
I think there's inevitably going to be some ongoing maintenance work/technical debt for GIBCT even if it's not our focus, but I have some cycles today and this is a well-contained change - impacts GIDS admin interface only - so I will get it squared away.
