### ISSUE TITLE
Help identify exemplar test institutions

### ISSUE THREAD

**Issue by ben-USDS-damman** [department-of-veterans-affairs/gibct-data-service#220]
I am going through the code and looking at conditional branches in order to identify the sorts of institution fields should be used to identify some.

@saintsoup52 I bet you already have a list of institutions that are especially weird or are representative of large swaths of the kinds of institutions we want to validate. Can you share a list of facility codes we should think about using for manual and automated tests? Any help appreciated!

See also: department-of-veterans-affairs/vets.gov-team#1540

cc @mphprogrammer

**Comment by saintsoup52** [comment]
WILCO

**Comment by saintsoup52** [comment]
Here some good examples:
MOST POPULAR SCHOOLS
21907103	UNIVERSITY OF PHOENIX-ONLINE CAMPUS
21913148	AMERICAN PUBLIC UNIVERSITY SYSTEM

FLIGHT SCHOOLS
25043743	A T E OF TX INC DBA AMER FLYERS-ADDISON
25109164	MOORE AIR INC

CORRESPONDENCE SCHOOLS
 28003138	PENN FOSTER CAREER SCHOOL
28029006	US CAREER INSTITUTE

APPROVED SCHOOLS WITHOUT APPROVED PROGRAMS (should not appear)
20C06643	2010 MEDIA LLC
25443710	3D LEARNER INC
