### ISSUE TITLE
Only 12 schools DODMOU identified as DODMOU true...

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gibct-data-service#221]
@saintsoup52 Has identified a major difference between the old and new GIDS regarding the DODMOU column. 

1. Missing 5,126 DOD Approved schools in new GIDS
2. Only 12 schools are showing as DOD approved

I've checked the source CSV downloaded from the old GIDS in production. There are only 12 schools that would show as false. I inadvertently omitted the negation in the dodmou computation. The fix will be up shortly.

![screen shot 2017-03-10 at 12 47 17 pm](https://cloud.githubusercontent.com/assets/4104431/23806654/7e927f50-0590-11e7-8ebc-48720a5493fe.png)

@saintsoup52 Is there anyone I can contact for the actual files used to populate the old GIDS in production?

**Comment by saneshark** [comment]
@mphprogrammer I thought you were able to pull the CSVs from staging and that they were the same ones uploaded to production. Is this not the case?

My understanding was that dev and staging had the same set of CSVs uploaded.

**Comment by mphprogrammer** [comment]
I pulled them from production, downloading from the old GIDS.

**Comment by mphprogrammer** [comment]
@saneshark @saintsoup52 MOU was changed on March 02 in production, I need to know if they've built the preview database...

**Comment by mphprogrammer** [comment]
And I think we are getting our terminology a bit confused. There is staging/production versions of the old GIDS, but there is a Preview and Production version of the database on each. So, I am getting the Preview version of the data on the Production GIDS.

**Comment by mphprogrammer** [comment]
What I can do is run both old and new GIDS locally, and If I had the absolute correct versions of the CSV source files, can build local copies of the data and compare those.

**Comment by mphprogrammer** [comment]
This was due to a missing ! inverting the logic, and is addressed in an open PR.

**Comment by mphprogrammer** [comment]
This has been merged, moving to done.
