### ISSUE TITLE
"False"s & Zeros should be Blanks in export csv

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#232]
Was just reviewing the new export csv and y'all are doing an amazing job.

I did notice one small thing... the new export file has lots of "False" and "0" where they used to be blanks. Since we use this export csv to run the public facing data dashboards, we need those fields to be appear as blanks in the csv.

The following fields are showing "False" when it should just be blank:
* Yr
* Student_veteran
* Poe
* Eight_keys
* Dodmou
* Accredited
* Caution_flag

The following fields are showing "0" when it should just be blank:
* Gibill
* P911_tuition_fees	
* P911_recipients	
* P911_yellow_ribbon	
* P911_yr_recipients
* All the complaint field

Last note... in the export csv all the headers are lowercase... not sure why the headers in this file all have the first letter capitalized.

Old (top) vs new file (bottom)
![image](https://cloud.githubusercontent.com/assets/4397508/24205778/bbe301d4-0ef2-11e7-8761-079af714a3a5.png)

**Comment by mphprogrammer** [comment]
The institution migration files are currently defaulting to 0 and false. @U-DON, I would like to make sure setting these fields to default to NULL (blank) in a new migration won't impact you.

**Comment by U-DON** [comment]
@mphprogrammer I think it should be fine for boolean values, but sometimes I see data where numeric data is null, which becomes more of an issue. I'll have to handle those possible null values and treat them as 0 on the front end.

**Comment by saneshark** [comment]
@mphprogrammer if this is not a heavy lift on the backend lets try to tackle it for launch. Assigning this one to you.

**Comment by saneshark** [comment]
@mphprogrammer do we have an update on this one? Can we close?

**Comment by mphprogrammer** [comment]
Need to write tests for it. Will have it up today.

**Comment by mphprogrammer** [comment]
@U-DON in light of yesterday's issues with 0s where nils should be (BAH, Tutition, etc for schools like AARHUS), would it be possible to remove the 0 as default? This would eliminate massaging exported values, and allow you to place a marker like '-' when no value is supplied.

**Comment by U-DON** [comment]
@mphprogrammer As of v1, I'm still getting `null` for numeric attributes, so this should be fine. We're defaulting them to 0 for calculations on the front end for the time being, but can eventually use the `null` values to improve the UX.

**Comment by mphprogrammer** [comment]
FYI PR #236 is up to fix this.
