### ISSUE TITLE
Exported CSV column headers should be lowercase

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/gibct-data-service#237]
Mentioned in #232. The PR that fixes the main issue in #232 doesn't address the export column case, so filing a separate issue to track that so it doesn't get lost.

**Comment by saneshark** [comment]
Thanks @patrickvinograd if this deviates from what we currently do in production for the export, then I think we should definitely prioritize this for before launch. Thoughts?

**Comment by patrickvinograd** [comment]
Seems like an easy fix, agree we should do it to avoid any confusion/deviation.
