### ISSUE TITLE
Exported files have no file type

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#251]
I tried exporting a number of the CSV files and the big institution file and they were an "unknown file type".

![image](https://cloud.githubusercontent.com/assets/4397508/24955897/4ba8f768-1f53-11e7-8b9b-19efb7ce2c79.png)

![image](https://cloud.githubusercontent.com/assets/4397508/24955883/3c68a32a-1f53-11e7-9829-f5f469747d20.png)

I was able to eventually open them in notepad but that is a cumbersome process to get them back into an excel format.

@mphprogrammer @saneshark

**Comment by patrickvinograd** [comment]
Should add `text/csv` Content-Type header during download.

**Comment by mphprogrammer** [comment]
Yup, missed that. A quick workaround would be to rename the file with a .csv extension.

**Comment by saneshark** [comment]
I think Rails will be smart enough to negotiate the content-type based on extension, but doesn't hurt to do both.

**Comment by patrickvinograd** [comment]
When I download this using Chrome on a mac, it is serving a content-type of `text/csv`, and Chrome puts it in my Downloads folder with a reasonable filename ("Institution.csv", "Hcm.csv"). And if I open it from the Finder it opens in Excel. The latter is dependent on the desktop setup of the user, I don't have a windows machine to test on. 

The only server-side thing I see missing is that we are serving a Content-Disposition header but it doesn't have the `filename` parameter in that header, which may account for the missing extension on Windows. Maybe chrome derives it from the Content-Type but IE or whatever browser was used above does not?
