### ISSUE TITLE
Clicking on green "Upload a file" button produces error button

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#253]
Starting from the "uploads" page that lists the most current uploads to the DS, I clicked on the green "Upload a File" button 

![image](https://cloud.githubusercontent.com/assets/4397508/24956203/94d14dd6-1f54-11e7-80c8-9eecce3afb0d.png)

and I was taken to the dashboard page (also another button) and was given the following error message.

![image](https://cloud.githubusercontent.com/assets/4397508/24956183/7c446618-1f54-11e7-8764-90c495ff44e4.png)

So two things... 
1) I did not try to upload a file so this is an odd error message and 
2) there really is no need for this button now that both just go back to the dashboard page. 

@mphprogrammer @saneshark

**Comment by patrickvinograd** [comment]
It's supposed to take you to the file upload form - it's only bouncing back to the dashboard because of the error.

**Comment by patrickvinograd** [comment]
During error refactor handling this logic got dropped from UploadController#new:
```
return if @upload.csv_type.blank? || @upload.csv_type_check?
```
Specifically the upload.cvs_type.blank? condition.

**Comment by mphprogrammer** [comment]
The "upload" button should be removed ... since this function has been removed from the dashboard, I had changed the logic to disallow blank? csv_type

**Comment by saneshark** [comment]
Confirming, we will be removing the "generic" upload capability. It's already been removed from the dashboard. It should be removed from the upload history page as well. The only way to upload CSV is by selecting one of the specific types from the dashboard.

**Comment by leannammiller** [comment]
@saneshark sounds like this can be closed?

**Comment by saneshark** [comment]
I will let @patrickvinograd address this as part of his work on a related ticket.
