### ISSUE TITLE
Change "Create" button to "Upload"

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#255]
On the "Upload" page the blue button call to action is "Create" which doesn't really make sense in this context.

Since this is the upload page, the blue button should say "Upload"

![image](https://cloud.githubusercontent.com/assets/4397508/24957144/ba8500f0-1f58-11e7-8d03-f170d983bdf8.png)

@saneshark @mphprogrammer

**Comment by saneshark** [comment]
The ability to do generic file uploads is going away entirely. You will only be able to do the upload using the dashboard, which should make this view irrelevant.

@mphprogrammer can this be closed? I think we need to remove this view logic as well. Also, I want us to do some tests around this and make sure the redirect sends you back to the dashboard with appropriate errors.

**Comment by leannammiller** [comment]
@saneshark can you confirm this is a launch blocker?

**Comment by patrickvinograd** [comment]
This form still exists when you get to it from the dashboard - because you need to choose the file and specify the comment. I will update the button label.
