### ISSUE TITLE
"FALSE" in institution file should be blank

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#257]
In the following fields a value of "False" should show up as a blank in the institution data download file:
* correspondence
* flight
* yr
* poe
* accredited

Here is what the current production data dashboard looks like:
![image](https://cloud.githubusercontent.com/assets/4397508/24958694/3119dd3a-1f5e-11e7-8f19-00105668a64a.png)

Here is what the staging version is producing:
![image](https://cloud.githubusercontent.com/assets/4397508/24958706/3fff76d4-1f5e-11e7-88f2-2643fc53bc27.png)

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
@mphprogrammer I'm assigning this one to you to address.

**Comment by leannammiller** [comment]
@saneshark can you confirm that this launch blocker?

**Comment by saneshark** [comment]
@mphprogrammer please prioritize this one. And yes, this is a launch blocker IMO

**Comment by mphprogrammer** [comment]
@saintsoup52 Just to clarify, these fields are to be null in the export even if they have a 'N' value in weams?

**Comment by mphprogrammer** [comment]
@saintsoup52 Is this a general rule for all booleans in the institution table, all false booleans are to be exported as blanks?

**Comment by mphprogrammer** [comment]
@saintsoup52 I am looking quickly at the null/false thing. The data is represented fine in the Institution table. It is null where the csv rows are blank, false where they are ‘N’, and true where they are ‘Y’. However, you want to change the representation of the data from FALSE (as it is correctly stated) to ‘’ (blanks) when we export all boolean values to a CSV?

**Comment by saintsoup52** [comment]
Correct... those "N" should appear as (blanks).

The basic reason is that we don't want to imply that OJT's are choosing not to be a POE or YR program because in fact they are prohibited. This is the same reason we hide the "Veterans Programs" section for those type of programs.
