### ISSUE TITLE
New ED accreditation database breaks CT tool & caution flags

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#265]
The Department of Education just updated their accreditation database for the first time in over a year and they made substantial changes to the way that database works. Unfortunately this means it will break the data service and the CT itself if we try to upload it.

https://ope.ed.gov/accreditation/GetDownloadFile.aspx

Specifically, they added 4 new columns and substantially changed the codes used in the “Accreditation_Status” field. We currently use the “Accreditation_Status” field to place a caution flag on schools that are on probation by their accreditors. 

As a CT team we need to review the new Accreditation_Status codes (see below) and determine which ones should trigger a caution flag.  Additionally, ED has added links explaining the reasons for particular accreditation determinations and we should probably be highlighting those links in the caution flags themselves. Lastly, whatever changes we decide will need to be hardcoded in the data service and in the tool itself.

New Accreditation Status Codes:
•	Accreditation Reaffirmed:  Warning Removed
•	Accreditation Reaffirmed: Probation Removed
•	Grant Substantive Change: Degree
•	Grant Substantive Change: Other
•	Grant Substantive Change: Ownership
•	Grant Substantive Change: Program
•	Heightened Monitoring or Focused Review
•	Initial Accreditation
•	Loss of Accreditation or Preaccreditation: Voluntary Withdrawal
•	Probation or Equivalent or a More Severe Status: Other
•	Probation or Equivalent or a More Severe Status: Probation
•	Probation or Equivalent or a More Severe Status: Show Cause
•	Removal of Show Cause Status
•	Renewal of Accreditation
•	Warning
•	Warning or Equivalent-Factors Affecting Academic Quality

Here is a glossary explaining what each of those codes mean;
https://ope.ed.gov/accreditation/Glossary.aspx

**Comment by mphprogrammer** [comment]
@melwoodard It looks like the VA EDU folks have not yet decided which of these new status codes will trigger the caution flags. However, once decided these need to be added to the InstitutionBuilder code responsible for adding caution flags and caution flag reasons. Is there any ETA on when a decision would be reached?

**Comment by mphprogrammer** [comment]
@saintsoup52 Is there any ETA on when the determination regarding which new statuses need to trigger flags?

**Comment by saintsoup52** [comment]
This is a little bit of a complicated issue and needs policy sign off from EDU folks. I imagine this will take about a week to resolve.

I have asked EDU that they should not hold up launch for this.

**Comment by melwoodard** [comment]
Moving to icebox until we get more info from the EDU team.

**Comment by leannammiller** [comment]
Leanna to F/U with education folks with Marc copied, as soon as we figure out which statuses need to trigger flags, Marc will implement

**Comment by leannammiller** [comment]
@saintsoup52 could you please clarify which statuses need to trigger the caution flags? or help point me to the right person to answer this?

**Comment by saintsoup52** [comment]
@leannammiller I am still working with EDU to figure this out. Since this is complicated policy issue for them that needs to be cleared within their internal process.

Sorry for the delay. Thank you for your patience.

**Comment by leannammiller** [comment]
@saintsoup52 just pinging for status here.

**Comment by saintsoup52** [comment]
@leannammiller Thanks for checking in... it is still going through EDU concurrence.

**Comment by leannammiller** [comment]
@saintsoup52 - could you please provide an update on this?

**Comment by saintsoup52** [comment]
EDU has approved the accreditation codes for what should trigger a caution flag on the GI Bill CT. 

They are now putting the final touches on the business rules (e.g., should this apply to school level probations or program level probations). I would say we are 90% done with those business rules.

I think it would be helpful if you gave EDU a time frame for when developers can come on board and that will force them to finish this process. I think if you have them a week (2 weeks at the most) that should be sufficient time.

**Comment by leannammiller** [comment]
@saintsoup52 we are working to define the roadmap for GIBCT now.

**Comment by patrickvinograd** [comment]
There is some tricky work in terms of DB queries here so giving it a conservative estimate.

**Comment by jholton** [comment]
Closing as outdated.
