### ISSUE TITLE
Complaint CSV Data File upload Issues

### ISSUE THREAD

**Issue by jmcneal65** [department-of-veterans-affairs/gibct-data-service#276]
Complaint CSV Data File was uploaded succeeded but with following rows should be checked:  
•	Complaint
The following rows should be checked: 
•	Row Line 40 : can't be blank
•	Row Line 73 : can't be blank
•	Row Line 112 : can't be blank
•	Row Line 125 : can't be blank
•	Row Line 140 : can't be blank
•	Row Line 142 : can't be blank
•	Row Line 149 : can't be blank
•	Row Line 154 : can't be blank
•	Row Line 172 : can't be blank
•	Row Line 182 : can't be blank
•	Row Line 212 : can't be blank
•	Row Line 223 : can't be blank
•	Row Line 235 : can't be blank
•	Row Line 243 : can't be blank
•	Row Line 249 : can't be blank
•	Row Line 261 : can't be blank
•	Row Line 271 : can't be blank
•	Row Line 277 : can't be blank
•	Row Line 287 : can't be blank
•	Row Line 288 : can't be blank
•	Row Line 289 : can't be blank
•	Row Line 296 : can't be blank
•	Row Line 297 : can't be blank
•	Row Line 308 : can't be blank
•	Row Line 319 : can't be blank
•	Row Line 329 : can't be blank
•	Row Line 332 : can't be blank
•	Row Line 342 : can't be blank
•	Row Line 343 : can't be blank
•	Row Line 346 : can't be blank
•	Row Line 353 : can't be blank
•	Row Line 369 : can't be blank
•	Row Line 378 : can't be blank
•	Row Line 383 : can't be blank
•	Row Line 389 : can't be blank
•	Row Line 397 : can't be blank
•	Row Line 412 : can't be blank
•	Row Line 413 : can't be blank
•	Row Line 414 : can't be blank
•	Row Line 423 : can't be blank
•	Row Line 434 : can't be blank
•	Row Line 458 : can't be blank
•	Row Line 468 : can't be blank
•	Row Line 470 : can't be blank
•	Row Line 472 : can't be blank
•	Row Line 476 : can't be blank
•	Row Line 479 : can't be blank
•	Row Line 483 : can't be blank
•	Row Line 490 : can't be blank
•	Row Line 500 : can't be blank
•	Row Line 501 : can't be blank
•	Row Line 502 : can't be blank
•	Row Line 504 : can't be blank
•	Row Line 527 : can't be blank
•	Row Line 531 : can't be blank
•	Row Line 551 : can't be blank
•	Row Line 573 : can't be blank
•	Row Line 582 : can't be blank
•	Row Line 587 : can't be blank
•	Row Line 594 : can't be blank
•	Row Line 601 : can't be blank
•	Row Line 618 : can't be blank
•	Row Line 621 : can't be blank
•	Row Line 630 : can't be blank
•	Row Line 644 : can't be blank
•	Row Line 646 : can't be blank
•	Row Line 658 : can't be blank
•	Row Line 659 : can't be blank
•	Row Line 661 : can't be blank
•	Row Line 665 : can't be blank
•	Row Line 670 : can't be blank
•	Row Line 671 : can't be blank
•	Row Line 696 : can't be blank
•	Row Line 698 : can't be blank
•	Row Line 700 : can't be blank
•	Row Line 714 : can't be blank
•	Row Line 715 : can't be blank
•	Row Line 727 : can't be blank
•	Row Line 728 : can't be blank
•	Row Line 734 : can't be blank
•	Row Line 741 : can't be blank
•	Row Line 745 : can't be blank
•	Row Line 778 : can't be blank
•	Row Line 799 : can't be blank
•	Row Line 803 : can't be blank
•	Row Line 821 : can't be blank
•	Row Line 822 : can't be blank
•	Row Line 824 : can't be blank
•	Row Line 869 : can't be blank
•	Row Line 870 : can't be blank
•	Row Line 875 : can't be blank
•	Row Line 877 : can't be blank
•	Row Line 915 : can't be blank
•	Row Line 916 : can't be blank
•	Row Line 917 : can't be blank
•	Row Line 935 : can't be blank
•	Row Line 942 : can't be blank
•	Row Line 960 : can't be blank
•	Row Line 961 : can't be blank
•	Row Line 1010 : can't be blank
•	Row Line 1011 : can't be blank
•	Row Line 1012 : can't be blank
•	Row Line 1041 : can't be blank
•	Row Line 1085 : can't be blank
•	Row Line 1089 : can't be blank
•	Row Line 1093 : can't be blank
•	Row Line 1110 : can't be blank
•	Row Line 1126 : can't be blank
•	Row Line 1131 : can't be blank
•	Row Line 1133 : can't be blank
•	Row Line 1149 : can't be blank
•	Row Line 1153 : can't be blank
•	Row Line 1183 : can't be blank
•	Row Line 1190 : can't be blank
•	Row Line 1193 : can't be blank
•	Row Line 1201 : can't be blank
•	Row Line 1223 : can't be blank
•	Row Line 1224 : can't be blank
•	Row Line 1248 : can't be blank
•	Row Line 1249 : can't be blank
•	Row Line 1258 : can't be blank
•	Row Line 1260 : can't be blank
•	Row Line 1262 : can't be blank
•	Row Line 1273 : can't be blank
•	Row Line 1291 : can't be blank
•	Row Line 1303 : can't be blank
•	Row Line 1308 : can't be blank
•	Row Line 1320 : can't be blank
•	Row Line 1321 : can't be blank
•	Row Line 1322 : can't be blank
•	Row Line 1323 : can't be blank
•	Row Line 1324 : can't be blank
•	Row Line 1343 : can't be blank
•	Row Line 1363 : can't be blank
•	Row Line 1389 : can't be blank
•	Row Line 1392 : can't be blank
•	Row Line 1402 : can't be blank
•	Row Line 1403 : can't be blank
•	Row Line 1416 : can't be blank
•	Row Line 1419 : can't be blank
•	Row Line 1428 : can't be blank
•	Row Line 1437 : can't be blank
•	Row Line 1447 : can't be blank
•	Row Line 1454 : can't be blank
•	Row Line 1476 : can't be blank
•	Row Line 1484 : can't be blank
•	Row Line 1490 : can't be blank
•	Row Line 1492 : can't be blank
•	Row Line 1511 : can't be blank
•	Row Line 1524 : can't be blank
•	Row Line 1525 : can't be blank
•	Row Line 1533 : can't be blank
•	Row Line 1563 : can't be blank
•	Row Line 1566 : can't be blank
•	Row Line 1567 : can't be blank
•	Row Line 1568 : can't be blank
•	Row Line 1575 : can't be blank
•	Row Line 1580 : can't be blank
•	Row Line 1588 : can't be blank
•	Row Line 1606 : can't be blank
•	Row Line 1607 : can't be blank
•	Row Line 1612 : can't be blank
•	Row Line 1632 : can't be blank
•	Row Line 1634 : can't be blank
•	Row Line 1640 : can't be blank
•	Row Line 1655 : can't be blank
•	Row Line 1692 : can't be blank
•	Row Line 1701 : can't be blank
•	Row Line 1710 : can't be blank
•	Row Line 1714 : can't be blank
•	Row Line 1721 : can't be blank
•	Row Line 1725 : can't be blank
•	Row Line 1728 : can't be blank
•	Row Line 1734 : can't be blank
•	Row Line 1737 : can't be blank
•	Row Line 1742 : can't be blank
•	Row Line 1756 : can't be blank
•	Row Line 1762 : can't be blank
•	Row Line 1763 : can't be blank
•	Row Line 1768 : can't be blank
•	Row Line 1771 : can't be blank
•	Row Line 1781 : can't be blank
•	Row Line 1783 : can't be blank
•	Row Line 1793 : can't be blank
•	Row Line 1799 : can't be blank
•	Row Line 1805 : can't be blank
•	Row Line 1808 : can't be blank
•	Row Line 1835 : can't be blank
•	Row Line 1836 : can't be blank
•	Row Line 1844 : can't be blank
•	Row Line 1849 : can't be blank
•	Row Line 1903 : can't be blank
•	Row Line 1921 : can't be blank
•	Row Line 1954 : can't be blank
•	Row Line 1981 : can't be blank
•	Row Line 1984 : can't be blank
•	Row Line 1993 : can't be blank
•	Row Line 1996 : can't be blank
•	Row Line 2020 : can't be blank
•	Row Line 2026 : can't be blank
•	Row Line 2039 : can't be blank
•	Row Line 2046 : can't be blank
•	Row Line 2054 : can't be blank
•	Row Line 2059 : can't be blank
•	Row Line 2064 : can't be blank
•	Row Line 2067 : can't be blank
•	Row Line 2086 : can't be blank
•	Row Line 2093 : can't be blank
•	Row Line 2099 : can't be blank
•	Row Line 2105 : can't be blank
•	Row Line 2140 : can't be blank
•	Row Line 2147 : can't be blank
•	Row Line 2164 : can't be blank
•	Row Line 2166 : can't be blank
•	Row Line 2179 : can't be blank
•	Row Line 2180 : can't be blank
•	Row Line 2183 : can't be blank
•	Row Line 2185 : can't be blank
•	Row Line 2187 : can't be blank
•	Row Line 2189 : can't be blank
•	Row Line 2191 : can't be blank
•	Row Line 2203 : can't be blank
•	Row Line 2212 : can't be blank
•	Row Line 2239 : can't be blank
•	Row Line 2261 : can't be blank
•	Row Line 2276 : can't be blank
•	Row Line 2281 : can't be blank
•	Row Line 2287 : can't be blank
•	Row Line 2295 : can't be blank
•	Row Line 2297 : can't be blank
•	Row Line 2302 : can't be blank
•	Row Line 2310 : can't be blank
•	Row Line 2311 : can't be blank
•	Row Line 2314 : can't be blank
•	Row Line 2317 : can't be blank
•	Row Line 2325 : can't be blank
•	Row Line 2333 : can't be blank
•	Row Line 2338 : can't be blank
•	Row Line 2382 : can't be blank
•	Row Line 2392 : can't be blank
•	Row Line 2400 : can't be blank
•	Row Line 2411 : can't be blank
•	Row Line 2414 : can't be blank
•	Row Line 2419 : can't be blank
•	Row Line 2421 : can't be blank
•	Row Line 2428 : can't be blank
•	Row Line 2429 : can't be blank
•	Row Line 2443 : can't be blank
•	Row Line 2448 : can't be blank
•	Row Line 2473 : can't be blank
•	Row Line 2480 : can't be blank
•	Row Line 2486 : can't be blank
•	Row Line 2498 : can't be blank
•	Row Line 2499 : can't be blank
•	Row Line 2509 : can't be blank
•	Row Line 2511 : can't be blank
•	Row Line 2526 : can't be blank
•	Row Line 2531 : can't be blank
•	Row Line 2550 : can't be blank
•	Row Line 2560 : can't be blank
•	Row Line 2580 : can't be blank
•	Row Line 2601 : can't be blank
•	Row Line 2606 : can't be blank
•	Row Line 2613 : can't be blank
•	Row Line 2619 : can't be blank
•	Row Line 2623 : can't be blank
•	Row Line 2653 : can't be blank
•	Row Line 2681 : can't be blank
•	Row Line 2694 : can't be blank
•	Row Line 2700 : can't be blank
•	Row Line 2717 : can't be blank
•	Row Line 2764 : can't be blank
•	Row Line 2769 : can't be blank
•	Row Line 2784 : can't be blank
•	Row Line 2790 : can't be blank
•	Row Line 2797 : can't be blank
•	Row Line 2798 : can't be blank
•	Row Line 2799 : can't be blank
•	Row Line 2800 : can't be blank
•	Row Line 2817 : can't be blank
•	Row Line 2822 : can't be blank
•	Row Line 2834 : can't be blank
•	Row Line 2838 : can't be blank
•	Row Line 2845 : can't be blank
•	Row Line 2854 : can't be blank
•	Row Line 2874 : can't be blank
•	Row Line 2896 : can't be blank
•	Row Line 2911 : can't be blank
•	Row Line 2933 : can't be blank
•	Row Line 2935 : can't be blank
•	Row Line 2950 : can't be blank
•	Row Line 2960 : can't be blank
•	Row Line 2961 : can't be blank
•	Row Line 2963 : can't be blank
•	Row Line 2972 : can't be blank
•	Row Line 2976 : can't be blank
•	Row Line 2983 : can't be blank
•	Row Line 2991 : can't be blank
•	Row Line 2993 : can't be blank
•	Row Line 2995 : can't be blank
•	Row Line 2996 : can't be blank
•	Row Line 3001 : can't be blank
•	Row Line 3007 : can't be blank
•	Row Line 3011 : can't be blank
•	Row Line 3014 : can't be blank
•	Row Line 3023 : can't be blank
•	Row Line 3041 : can't be blank
•	Row Line 3043 : can't be blank
•	Row Line 3056 : can't be blank
•	Row Line 3064 : can't be blank
•	Row Line 3073 : can't be blank
•	Row Line 3082 : can't be blank
•	Row Line 3130 : can't be blank
•	Row Line 3136 : can't be blank
•	Row Line 3140 : can't be blank
•	Row Line 3144 : can't be blank
•	Row Line 3164 : can't be blank
•	Row Line 3165 : can't be blank
•	Row Line 3168 : can't be blank
•	Row Line 3172 : can't be blank
•	Row Line 3175 : can't be blank
•	Row Line 3177 : can't be blank
•	Row Line 3181 : can't be blank
•	Row Line 3184 : can't be blank
•	Row Line 3236 : can't be blank
•	Row Line 3237 : can't be blank
•	Row Line 3322 : can't be blank
•	Row Line 3332 : can't be blank
•	Row Line 3374 : can't be blank
•	Row Line 3383 : can't be blank
•	Row Line 3414 : can't be blank
•	Row Line 3416 : can't be blank
•	Row Line 3417 : can't be blank
•	Row Line 3418 : can't be blank
•	Row Line 3587 : can't be blank
•	Row Line 3624 : can't be blank
•	Row Line 3880 : can't be blank
•	Row Line 3917 : can't be blank
•	Row Line 3923 : can't be blank
•	Row Line 3927 : can't be blank
•	Row Line 3928 : can't be blank
•	Row Line 3931 : can't be blank
•	Row Line 3938 : can't be blank
•	Row Line 3968 : can't be blank
•	Row Line 3969 : can't be blank
•	Row Line 3970 : can't be blank
•	Row Line 3971 : can't be blank
•	Row Line 3972 : can't be blank
•	Row Line 3973 : can't be blank
•	Row Line 3974 : can't be blank
•	Row Line 3975 : can't be blank
•	Row Line 3976 : can't be blank
•	Row Line 3978 : can't be blank
•	Row Line 3998 : can't be blank
•	Row Line 4069 : can't be blank
•	Row Line 4078 : can't be blank
•	Row Line 4100 : can't be blank
•	Row Line 4197 : can't be blank
•	Row Line 4232 : can't be blank
•	Row Line 4260 : can't be blank
•	Row Line 4262 : can't be blank
•	Row Line 4309 : can't be blank
•	Row Line 4341 : can't be blank
•	Row Line 4348 : can't be blank
•	Row Line 4387 : can't be blank
•	Row Line 4389 : can't be blank
•	Row Line 4398 : can't be blank
•	Row Line 4446 : can't be blank
•	Row Line 4487 : can't be blank
•	Row Line 4630 : can't be blank
•	Row Line 4641 : can't be blank
•	Row Line 4670 : can't be blank
•	Row Line 4675 : can't be blank
•	Row Line 4679 : can't be blank
•	Row Line 4727 : can't be blank
•	Row Line 4733 : can't be blank
•	Row Line 4855 : can't be blank
•	Row Line 4868 : can't be blank
•	Row Line 4892 : can't be blank
•	Row Line 4895 : can't be blank
•	Row Line 4935 : can't be blank
•	Row Line 4951 : can't be blank
•	Row Line 4968 : can't be blank
•	Row Line 4970 : can't be blank
•	Row Line 5108 : can't be blank
•	Row Line 5129 : can't be blank
•	Row Line 5189 : can't be blank
•	Row Line 5192 : can't be blank
•	Row Line 5193 : can't be blank
•	Row Line 5202 : can't be blank
•	Row Line 5226 : can't be blank
•	Row Line 5252 : can't be blank
•	Row Line 5253 : can't be blank
•	Row Line 5276 : can't be blank
•	Row Line 5308 : can't be blank
•	Row Line 5313 : can't be blank
•	Row Line 5339 : can't be blank
•	Row Line 5348 : can't be blank
•	Row Line 5367 : can't be blank
•	Row Line 5394 : can't be blank
•	Row Line 5443 : can't be blank
•	Row Line 5444 : can't be blank
•	Row Line 5492 : can't be blank
•	Row Line 5496 : can't be blank
•	Row Line 5499 : can't be blank
•	Row Line 5537 : can't be blank
•	Row Line 5592 : can't be blank
•	Row Line 5623 : can't be blank
•	Row Line 5625 : can't be blank
•	Row Line 5677 : can't be blank
•	Row Line 5695 : can't be blank
•	Row Line 5714 : can't be blank
•	Row Line 5719 : can't be blank
•	Row Line 5777 : can't be blank
•	Row Line 5792 : can't be blank
•	Row Line 5834 : can't be blank
•	Row Line 5841 : can't be blank
•	Row Line 5847 : can't be blank
•	Row Line 5854 : can't be blank
•	Row Line 5855 : can't be blank
•	Row Line 5869 : can't be blank
•	Row Line 5949 : can't be blank
•	Row Line 5965 : can't be blank
•	Row Line 5967 : can't be blank
•	Row Line 5992 : can't be blank
•	Row Line 6033 : can't be blank
•	Row Line 6044 : can't be blank
•	Row Line 6056 : can't be blank
•	Row Line 6066 : can't be blank
•	Row Line 6067 : can't be blank
•	Row Line 6074 : can't be blank
•	Row Line 6086 : can't be blank
•	Row Line 6095 : can't be blank
•	Row Line 6099 : can't be blank
•	Row Line 6131 : can't be blank
•	Row Line 6133 : can't be blank
•	Row Line 6163 : can't be blank
•	Row Line 6168 : can't be blank
•	Row Line 6248 : can't be blank
•	Row Line 6251 : can't be blank
•	Row Line 6256 : can't be blank
•	Row Line 6259 : can't be blank
•	Row Line 6261 : can't be blank
•	Row Line 6264 : can't be blank
•	Row Line 6286 : can't be blank
•	Row Line 6299 : can't be blank
•	Row Line 6301 : can't be blank
•	Row Line 6311 : can't be blank
•	Row Line 6326 : can't be blank
•	Row Line 6329 : can't be blank
•	Row Line 6332 : can't be blank
•	Row Line 6335 : can't be blank
•	Row Line 6341 : can't be blank
•	Row Line 6344 : can't be blank
•	Row Line 6350 : can't be blank
•	Row Line 6351 : can't be blank
•	Row Line 6357 : can't be blank
•	Row Line 6360 : can't be blank
•	Row Line 6364 : can't be blank
•	Row Line 6371 : can't be blank
•	Row Line 6373 : can't be blank
•	Row Line 6378 : can't be blank
•	Row Line 6380 : can't be blank
•	Row Line 6384 : can't be blank
•	Row Line 6388 : can't be blank
•	Row Line 6395 : can't be blank
•	Row Line 6400 : can't be blank
•	Row Line 6401 : can't be blank
•	Row Line 6406 : can't be blank
•	Row Line 6413 : can't be blank
•	Row Line 6418 : can't be blank
•	Row Line 6424 : can't be blank
•	Row Line 6443 : can't be blank
•	Row Line 6445 : can't be blank
•	Row Line 6456 : can't be blank
•	Row Line 6476 : can't be blank
•	Row Line 6495 : can't be blank
•	Row Line 6499 : can't be blank
•	Row Line 6559 : can't be blank
•	Row Line 6580 : can't be blank
•	Row Line 6592 : can't be blank
•	Row Line 6593 : can't be blank
•	Row Line 6595 : can't be blank
•	Row Line 6602 : can't be blank
•	Row Line 6604 : can't be blank
•	Row Line 6610 : can't be blank
•	Row Line 6621 : can't be blank
•	Row Line 6637 : can't be blank
•	Row Line 6638 : can't be blank
•	Row Line 6645 : can't be blank
•	Row Line 6647 : can't be blank
•	Row Line 6648 : can't be blank
•	Row Line 6653 : can't be blank
•	Row Line 6681 : can't be blank
•	Row Line 6683 : can't be blank
•	Row Line 6686 : can't be blank
•	Row Line 6687 : can't be blank
•	Row Line 6688 : can't be blank
•	Row Line 6692 : can't be blank
•	Row Line 6700 : can't be blank
•	Row Line 6703 : can't be blank
•	Row Line 6704 : can't be blank
•	Row Line 6707 : can't be blank
•	Row Line 6709 : can't be blank
•	Row Line 6715 : can't be blank
•	Row Line 6716 : can't be blank
•	Row Line 6739 : can't be blank
•	Row Line 6742 : can't be blank
•	Row Line 6746 : can't be blank
•	Row Line 6754 : can't be blank
•	Row Line 6758 : can't be blank
•	Row Line 6760 : can't be blank
•	Row Line 6761 : can't be blank
•	Row Line 6763 : can't be blank
•	Row Line 6766 : can't be blank
•	Row Line 6771 : can't be blank
•	Row Line 6775 : can't be blank
•	Row Line 6779 : can't be blank
•	Row Line 6788 : can't be blank
•	Row Line 6792 : can't be blank
•	Row Line 6794 : can't be blank
•	Row Line 6796 : can't be blank
•	Row Line 6805 : can't be blank
•	Row Line 6810 : can't be blank
•	Row Line 6816 : can't be blank
•	Row Line 6826 : can't be blank
•	Row Line 6836 : can't be blank
•	Row Line 6840 : can't be blank
•	Row Line 6855 : can't be blank
•	Row Line 6870 : can't be blank
•	Row Line 6872 : can't be blank
•	Row Line 6873 : can't be blank
•	Row Line 6874 : can't be blank
•	Row Line 6876 : can't be blank
•	Row Line 6881 : can't be blank
•	Row Line 6882 : can't be blank
•	Row Line 6888 : can't be blank
•	Row Line 6913 : can't be blank
•	Row Line 6915 : can't be blank
•	Row Line 6918 : can't be blank
•	Row Line 6939 : can't be blank
•	Row Line 6946 : can't be blank
•	Row Line 6949 : can't be blank
•	Row Line 6950 : can't be blank
•	Row Line 6963 : can't be blank
•	Row Line 7025 : can't be blank
•	Row Line 7041 : can't be blank
•	Row Line 7061 : can't be blank
•	Row Line 7073 : can't be blank
•	Row Line 7099 : can't be blank
•	Row Line 7100 : can't be blank
•	Row Line 7105 : can't be blank
•	Row Line 7107 : can't be blank
•	Row Line 7116 : can't be blank
•	Row Line 7144 : can't be blank
•	Row Line 7158 : can't be blank
•	Row Line 7218 : can't be blank
•	Row Line 7226 : can't be blank
•	Row Line 7227 : can't be blank
•	Row Line 7245 : can't be blank
•	Row Line 7261 : can't be blank
•	Row Line 7266 : can't be blank
•	Row Line 7275 : can't be blank
•	Row Line 7279 : can't be blank
•	Row Line 7287 : can't be blank
•	Row Line 7358 : can't be blank
•	Row Line 7363 : can't be blank
•	Row Line 7386 : can't be blank
•	Row Line 7389 : can't be blank
•	Row Line 7401 : can't be blank
•	Row Line 7420 : can't be blank
•	Row Line 7441 : can't be blank
•	Row Line 7475 : can't be blank
•	Row Line 7495 : can't be blank
•	Row Line 7511 : can't be blank
•	Row Line 7538 : can't be blank
•	Row Line 7542 : can't be blank
•	Row Line 7582 : can't be blank
•	Row Line 7585 : can't be blank
•	Row Line 7586 : can't be blank
•	Row Line 7587 : can't be blank
•	Row Line 7599 : can't be blank
•	Row Line 7600 : can't be blank
•	Row Line 7601 : can't be blank
•	Row Line 7604 : can't be blank
•	Row Line 7605 : can't be blank
•	Row Line 7620 : can't be blank
•	Row Line 7627 : can't be blank
•	Row Line 7640 : can't be blank
•	Row Line 7666 : can't be blank
•	Row Line 7682 : can't be blank
•	Row Line 7692 : can't be blank
•	Row Line 7697 : can't be blank
•	Row Line 7701 : can't be blank
•	Row Line 7764 : can't be blank
•	Row Line 7806 : can't be blank
•	Row Line 7826 : can't be blank
•	Row Line 7827 : can't be blank
•	Row Line 7831 : can't be blank
•	Row Line 7837 : can't be blank
•	Row Line 7842 : can't be blank
•	Row Line 7844 : can't be blank
•	Row Line 7894 : can't be blank
•	Row Line 7903 : can't be blank
•	Row Line 7909 : can't be blank
•	Row Line 7915 : can't be blank
•	Row Line 7926 : can't be blank
•	Row Line 7928 : can't be blank
•	Row Line 7935 : can't be blank
•	Row Line 7939 : can't be blank
•	Row Line 7940 : can't be blank
•	Row Line 7957 : can't be blank
•	Row Line 7960 : can't be blank
•	Row Line 7965 : can't be blank
•	Row Line 7970 : can't be blank
•	Row Line 7978 : can't be blank
•	Row Line 7979 : can't be blank
•	Row Line 7988 : can't be blank
•	Row Line 8003 : can't be blank
•	Row Line 8004 : can't be blank
•	Row Line 8020 : can't be blank
•	Row Line 8021 : can't be blank
•	Row Line 8028 : can't be blank
•	Row Line 8030 : can't be blank
•	Row Line 8033 : can't be blank
•	Row Line 8038 : can't be blank
•	Row Line 8039 : can't be blank
•	Row Line 8040 : can't be blank
•	Row Line 8041 : can't be blank
•	Row Line 8052 : can't be blank
•	Row Line 8053 : can't be blank
•	Row Line 8054 : can't be blank
•	Row Line 8055 : can't be blank
•	Row Line 8056 : can't be blank
•	Row Line 8057 : can't be blank
•	Row Line 8062 : can't be blank
•	Row Line 8068 : can't be blank
•	Row Line 8081 : can't be blank
•	Row Line 8085 : can't be blank
•	Row Line 8093 : can't be blank
•	Row Line 8095 : can't be blank
•	Row Line 8099 : can't be blank
•	Row Line 8103 : can't be blank
•	Row Line 8104 : can't be blank
•	Row Line 8109 : can't be blank
•	Row Line 8113 : can't be blank
•	Row Line 8119 : can't be blank, is not included in the list
The following headers should be checked: 
•	Level is a missing header
•	Case owner is a missing header
•	Submitted is a missing header
•	Closed is a missing header

**Comment by saintsoup52** [comment]
This file was downloaded from the old data service and uploaded in the staging data service... So we definitely need to check this.

Also it seems like the header errors should appear before the row line errors.

**Comment by mphprogrammer** [comment]
@saintsoup52 @jmcneal65 There are 2 issues here: (1) The error message was missing the column name (facility_code), which was fixed in a PR which will be merged after review, and (2) the missing column (facility_code) values reported for these records seems accurate. Those rows are missing facility code. Also, many of the rows in that Csv have an institution named "Z" with a facility_code of 0, which seems like an issue ...

**Comment by saintsoup52** [comment]
Understood... Definitely will help to have the column name and the row number to diagnose the issue.

What are the chance of moving the error for headers above the row errors. I would have never seen if we had not been cutting the text into github.

Lastly, what will happen if one of the critical columns is missing?

**Comment by mphprogrammer** [comment]
If a critical column is missing, the entire upload will fail. You will get an error:

"Failed to upload xxxx.csv: There was no saved XXXX data" 

This would be followed by a long sequence of line numbers, which wouldn't be too useful on a screen. I'll looking into making it look a little better ...

**Comment by mphprogrammer** [comment]
Closing this.
