### ISSUE TITLE
New crosswalk validation is ignoring alphanumeric

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#277]
In conducting the end to end testing I noticed that there we two fewer caution flags for the following schools:
21917411	ASHWORTH COLLEGE
25917411	ASHWORTH COLLEGE

The reason why these two schools are different is because they are not Title IV approved schools and therefore do not have an official ED IPEDS number.

However, in order to make the caution flags work, which are matched to the IPEDS, we created a VA only IPEDS number , "VAONLY001".

I am guessing this alphanumeric value is breaking something in the pipeline.

@mphprogrammer @mphprogrammer

**Comment by mphprogrammer** [comment]
I was wondering about why there was an IPEDS of VAONLY001. But I see the caution flags for these schools ...

![screen shot 2017-04-19 at 10 03 33 am](https://cloud.githubusercontent.com/assets/4104431/25183956/ff8d83e6-24e6-11e7-920d-263f62bdb9e3.png)

**Comment by mphprogrammer** [comment]
Let me see the export file to see if there are in there ...

**Comment by mphprogrammer** [comment]
It looks like the caution flags are in for my versions of the data. Perhaps the staging server is using a different data set? 

![screen shot 2017-04-19 at 10 08 51 am](https://cloud.githubusercontent.com/assets/4104431/25184196/bf9fb7f8-24e7-11e7-9c2a-f6f35bb95d6f.png)

**Comment by mphprogrammer** [comment]
I'll check that on staging ...

**Comment by mphprogrammer** [comment]
Caution flags for those schools are on staging too... This is a puzzler but looks good at the gids end.

**Comment by patrickvinograd** [comment]
Staging could definitely be a different data set at this point.

**Comment by mphprogrammer** [comment]
@saintsoup52 are you exporting the Institution data from staging or from your local machine?

**Comment by saintsoup52** [comment]
I exported the data file from the staging site and there was not a caution flag for those schools.

Hmm... This might just be a versioning issue.

**Comment by leannammiller** [comment]
@saintsoup52 were you able to confirm whether this was a versioning issue?

**Comment by saintsoup52** [comment]
This appears to be a versioning issue... which is a fancy way of saying user error... this user. :-) Sorry.
