### ISSUE TITLE
Data Service stripping "None's" from crosswalk file

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#282]
The data service is converting and changing files that are uploaded into the data service.

The most problematic area this happens is that when a crosswalk file is uploaded most of the schools and employers had a "None" in the OPE and IPEDS column. The "NONE" is an important placeholder for us to let us know that that we already researched this school and their is not a ED equivalent. There were nearly 40,000 "None"'s that took over a year to research.

If someone then downloads the file they just uploaded the "NONE"'s are all stripped from the file. This is a BIG problem for us because we can't tell which schools we already researched.

I noticed this seems to be happening with other files that they are converted when uploaded and then what we download is different then what we uploaded.

Please help... we are going to need to reconstruct the crosswalk from an older file because of this.

@mphprogrammer @leannammiller @melwoodard

**Comment by leannammiller** [comment]
@saintsoup52 thank you for letting us know. I'll talk to Marc and get back to you.

**Comment by mphprogrammer** [comment]
@saintsoup52  “NONE”, “NULL”, “PRIVACY SUPPRESSED” are stripped away on purpose. Having them in the data would change the results if they occurred in key fields or computations, and if in a displayed column would be confusing to people using the GIBCT. These tables were built only store the validated records used in the GIBCT.

The simplest fix I can think of right now is to save and work with the last uploaded CSV separately.

**Comment by saintsoup52** [comment]
I completely understand them being stripped away for the compiling of the CT data, but that changes the nature of the file we upload and then download again.

We use the DS to store several files, most importantly the crosswalk and this modification of the original data is very problematic.

Anything we can do to fix would be appreciated.

**Comment by mphprogrammer** [comment]
Are you guys using the Data Service to store CSV files that are being worked on because its a common and accessible place to share data?

**Comment by saintsoup52** [comment]
Yes... and because it is the most up to date version of the data

**Comment by leannammiller** [comment]
Hi @saintsoup52 - 

We unfortunately cannot accommodate this use case. It is outside of the intention of this tool. My suggestion would be to use GitHub or Sharepoint to collaborate on these documents.

**Comment by saintsoup52** [comment]
@leannammiller   Not to harp on this... but this exact functionality was one of the original requirements for the data service. And I thought this new data service was supposed to have at least the same functionality as the old tool.

In an email in Digital Service on March 10, 2016 responding to questions from original DS design team:
**@mphprogrammer** 
"What do you do with Crosswalk entries that do not have an OPEID or an IPED id?"

**@saintsoup52**
"They currently have a “NONE” in both columns. This is different than leaving it blank, because I know that “NONE” means we have researched it already and it is not a Title IV school… versus a blank which means it is new and we still need to review."

The crosswalk is the key that links all of these different data sets together and new way the data service handles this file makes it nearly impossible for us to keep it up to date.
