### ISSUE TITLE
IPEDS ID displaying incorrectly on GI Bill CT 

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#307]
I am not sure if this is a front end or back end issue, but the "ED IPEDS code:" is displaying incorrectly on the GI Bill Comparison Tool.

IPEDS unit IDs are 6-8 digit codes that never lead with a zero. For some reason the GI Bill CT or the data service is adding "zeroes" to the ID numbers to make them an eight digit code.

For example, Harvard University IPEDS is 166027.
https://www.vets.gov/gi-bill-comparison-tool/profile/31800121
![image](https://user-images.githubusercontent.com/4397508/33089854-f1cf259c-cebf-11e7-97f9-324a2ac50bea.png)

Here is another example, Oxnard College whose IPEDS is 120421
https://www.vets.gov/gi-bill-comparison-tool/profile/14953105
![image](https://user-images.githubusercontent.com/4397508/33089956-4e9103fe-cec0-11e7-90b9-7157a55e7b59.png)

While this is definitely not the most important issue with the CT, it probably doesn't reflect well on the VA when we are displaying incorrect info.

**Comment by jmcneal65** [comment]
What is the timeline to fix this?
