### ISSUE TITLE
Add Additional Key Data Points to the GIBCT Data Dashboards

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#313]
Add the additional data points from existing sources; Crosswalk, WEAMS, etc., to the data dashboards that are published to the GI Bill Comparison Tool. 

1. OPE 6 (derived from crosswalk)
2. School system name (IPEDS)
3. School system code (IPEDS)
4. Alias (IPEDS)

A "like to have" is to add this information to the additional information section of the school profile program.

**Comment by maneshkommidi** [comment]
@saintsoup52 @briangryth I got a clear picture on what needs to be done, please confirm the below information is correct or I'm I missing anything.

1) **OPE6** (**Crosswalk.csv**) and column name is **ope**
2) **School system name** (**IpedsHd.csv**) and column name is **instnm**
3) **School system code** (**IpedsHd.csv**) and column name is **unitid**
4) **Alias** (**IpedsHd.csv**) and column name is **ialias**

Thanks

**Comment by saintsoup52** [comment]
These data points need to be added to the institutions.csv file right after the "ope" column and before "insturl". These are 4 new columns that would be added.

1. **"ope_6":** This value is derived from the  "ope" in crosswalk file. Essentially it is the first 7 characters of the "ope" value with an added quotation mark at the end. For example, in the crosswalk the University of Phoenix OPE is "02098872". Their ope_6 should be  "020988" (taking away the last two numbers). 
 
The good news is that this derivation is already happening somewhere in code:
https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/converters/ope6_converter.rb

This character counting is one of the major reasons why keeping the quotations in the crosswalk is so important... that and all the leading zero's disappear without them.

2. **"school_system_name"**: (IpedsHd.csv) and column name is F1SYSNAM

3. **"school_system_code"**: (IpedsHd.csv) and column name is F1SYSCOD

4. **"alias"**: (IpedsHd.csv) and column name is ialias

**Comment by jholton** [comment]
Closed per linked PRs
