### ISSUE TITLE
Display non-approved schools in GI Bill CT Data Dashboards

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#314]
In order to ensure the data integrity of the data dashboards, we should add the following data points ONLY to the GI Bill CT dashboards:
1. Include information for non-approved school
2. Add a column for approval status

In FY 2016 almost 6% of Post-9/11 GI Bill Students attended a facility code that is no longer approved in WEAMS, going back to FY 2013 that number increases to over 15%

Here is an example of why this matters:
I was asked a random question from a VSO earlier this week about why the enrollment data on GI Bill CT for the XXXX University system seemed way off.   The Comparison Tool was showing GI Bill enrollment at XXXX Universities at only 4,100, but the other data they were seeing said it should be more like 10,000 GI Bill students.

I think I found the issue… XXX (FC XXXX) had 5,198 GI Bill Students in 2016 but now its approval has been withdrawn in WEAMS which means it does not show up on the CT. What happened to XXX? Is it like XXX University and they just moved somewhere and their facility code changed? Either way this is definitely an argument for including non-approved schools in the data dashboards.

**Comment by briangryth** [comment]
@nagaborra or @maneshkommidi - do you have specific questions that would help clarify this issue. 

The overall goal here is to allow non-approved schools to appear in the GIBCT Dashboard. Currently, only approved schools appear in the dashboard. 

Specific questions will help me get you the answers you need..

**Comment by saintsoup52** [comment]
Not that you asked, but I am pretty sure this is where the database is filtering out the non-approved schools.

https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/spec/factories/weams.rb

As for the new column indicating approval status, it should be labelled something like:

**Column Header:** 
"approval_status"

**Possible Responses:** 
- "Approved"
- "Approved for chapter 31 only" [not currently in the screen above]
- "Not approved"

**Comment by briangryth** [comment]
@nagaborra and @maneshkommidi does the above address your questions? Or do you need additional information? If so, please address let me know what you questions are? 

@saintsoup52 - are those the only possible responses? Or is that a question that Stephanie or Shay would need to verify?

**Comment by maneshkommidi** [comment]
@saintsoup52 while going through the WEAM model I observed the current logic for approved school's is **poo-status** field value must be **aprvd** or **applicable_law_code** value must be '**educational institution is not approved'** or '**educational institution is approved for chapter 31 only**'. 

Can you please let us know, based on what values we need to change the response for approval_status and also could you please confirm us whether we can remove the current existing logic for unapproved schools.

**Comment by maneshkommidi** [comment]
@saintsoup52  Thanks for clarification, yes the logic is in place. As per my understanding under this ticket we need to have new column **approval_status** and need to have the respective value for every entry in **Weam.csv** and **Institution.csv** and also send the approval_status data to UI.

**Comment by saintsoup52** [comment]
@maneshkommidi Thank you.

To be clear now every row with a facility code that appears in the WEAMS.csv file will now also appear in the Institutions.csv file, along with an approval status code.

As for the non-approved schools, they should NOT appear on the GI Bill Comparison Tool itself. Where and when in the process you separate the two lists (All vs approved) is up to you.

Hope that helps.

**Comment by saneshark** [comment]
It looks like only the migrations have been merged here, so work still remains on this ticket. Can someone confirm that this is not part of the Colmery Act changes?

**Comment by saintsoup52** [comment]
This change was actually required by a statute that passed before the Colmery Act that had been backlogged until now. Needless to say we are WAY behind in delivering this feature.

**Comment by zurbergram** [comment]
This has been deployed to production with https://github.com/department-of-veterans-affairs/gibct-data-service/releases/tag/gi-bill-data-service%2Fv0.0.86

This was done in support of business requirement:
https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/490

Related issues
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18880
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18882
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18920
