### ISSUE TITLE
School Closure Data 

### ISSUE THREAD

**Issue by briangryth** [department-of-veterans-affairs/gibct-data-service#322]
As part of the Colmery Act changes the GIBCT has to be able to display if and when an educational institution is closing. The data required to populate the GIBCT with this information is not currently in the GIDS. 

Therefore, the ticket is intended to add a new data file to the GIDS and to make that data accessible to the GIBCT front-end.

**New Data File**
[School Closure DRAFT 20180504.xlsx](https://github.com/department-of-veterans-affairs/gibct-data-service/files/1990346/School.Closure.DRAFT.20180504.xlsx)

*Associated Vets.gov-team ticket* [Issue #9369](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9369)

**Comment by maneshkommidi** [comment]
@jkassemi Sure will do

**Comment by maneshkommidi** [comment]
@briangryth Could you please let me know, what are all the columns that needs to be send to GIBCT from GIDS.

**Comment by briangryth** [comment]
@maneshkommidi the following are the columns to be sent:
Here are the columns that need to be brought into the GIDS:
·         school closing 
·         school closing date     
·         school closing message

**Comment by saneshark** [comment]
Code has been merged to staging and production! 🍻 🍾 🎉
