### ISSUE TITLE
Yellow Ribbon File 

### ISSUE THREAD

**Issue by briangryth** [department-of-veterans-affairs/gibct-data-service#323]
As Part of the Colmery Act changes the GIBCT is required to expand the amount of information about Yellow Ribbon programs is displayed. The data required to be displayed is not currently in the GIDS. 

This ticket is intended to add a new Yellow Ribbon data file to GIDS and make that data accessible to the GIBCT front-end. 

**New Data File**

[Master Copy of Yellow Ribbon.xlsb.zip](https://github.com/department-of-veterans-affairs/gibct-data-service/files/1992088/Master.Copy.of.Yellow.Ribbon.xlsb.zip) *Update at 5/10/2018 at 11:00 AM EDT*

*Associated Vets.gov team ticket:* [Issue #9365](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9365)

**Comment by briangryth** [comment]
@jkassemi @maneshkommidi - please note that data file has been replaced as on 5/10 at 11:00 am EDT. The file in the description is correct.

**Comment by maneshkommidi** [comment]
@jkassemi Sure will do

**Comment by maneshkommidi** [comment]
@briangryth Could you please let me know, what are all the columns that needs to be send to GIBCT from GIDS.

**Comment by saintsoup52** [comment]
We definitely need to use the following four columns from the YR file in the GIDS:
- Degree Level	
- Division Professional School	
- Number of Students	
- Contribution Amount

I need to figure out from EDU if there any rules to using this spreadsheet... e.g., are there some YR agreements that should NOT be appearing.

**Comment by jkassemi** [comment]
@maneshkommidi would appreciate the details on the implementation plan (GIDS API changes, and an overview of how they'll be connected to the new migrations) - would like to piece together any expected delay on deliverable.

**Comment by maneshkommidi** [comment]
@jkassemi once the migrations PR merged, will need to work on sending the YR related data to website through institutions hash.

**Comment by jkassemi** [comment]
What changes to the API are required to expose this new data, and how will it be exposed? Will there be a new attribute on the existing institutions API?

Also, how will the changes to the institution builder be made? I'm anticipating (but could be wrong, so I'm hoping for clarification here) that we'll either need a new table to store and version this information on publishing a new version, or we'll need to store this data in a new column on the institutions table.

**Comment by saneshark** [comment]
Code has been merged to staging and production! 🍻 🍾 🎉
