### ISSUE TITLE
STEM CIP code list and STEM Indicator

### ISSUE THREAD

**Issue by briangryth** [department-of-veterans-affairs/gibct-data-service#325]
According to the Colmery Act, the GIBCT needs to include an indicator whether an educational institution offer STEM programs. Currently, the GIDS does not include a list of the STEM CIP codes. This ticket is to add that information to the GIDS. Once added, this list will need to be cross referenced with one to the IPEDS files to verify that an institution offers a STEM program. 

Here is additional information from Patrick Campbell regarding this requirement:
-  I pulled this list of STEM fields from an ED Report (see attached file below)
- National Center for Education Statistics, Table A-1. List of STEM fields and associated 2000 CIP codes
- The Classification of Instructional Programs (CIP) codes corresponding to science, technology, engineering, and mathematics (STEM) fields were selected based on a U.S. Immigration and Customs Enforcement list of designated STEM degree programs.
- SOURCE: U.S. Department of Homeland Security, Immigration and Customs Enforcement, STEM Designated Degree Programs, retrieved April 30, 2010, from http://www.ice.gov/sevis/stemlist.htm. 

**New Data File**
[STEM CIP Code List 20180504.xlsx](https://github.com/department-of-veterans-affairs/gibct-data-service/files/1990384/STEM.CIP.Code.List.20180504.xlsx)

*Associated Vets.gov-team Ticket* [Issue #9371](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9371)

**Comment by maneshkommidi** [comment]
@briangryth Could you please let me know is this the correct approach
Do we need to import/export the stem_cip_code.csv in to GIDS and generate the boolean value in any of the existing table for stem check, if so what is the business logic to generate the stem check.

**Comment by briangryth** [comment]
@saintsoup52 - Do you have a recommendation for @maneshkommidi questions above? 

I believe we would need to import the stem_cip_code.csv into GIDS. 
That file would be used to check against an IPEDS file and if any of the stem codes match then the STEM program indication in GIBCT should be marked as TRUE.

**Comment by saintsoup52** [comment]
@briangryth @maneshkommidi  Here is how I would do it... 

I would allow EDU to upload the two files we need into the GIDS
1) STEM CIP List (file above)
2) IPEDS CIP File (see recent email)

I would match the unit_id from the IPEDS file and the "cross" from the crosswalk. I would import into the GIDS all the programs offered by that school (CIP codes where the CTOTALT >=0). Then if one of CIP codes that is offered matches the STEM CIP list then create a field called "stem_offered" = TRUE.

We only need the "stem_offered" field in the data dashboards.

From the IPEDS file I would import the following data:
**unit_id:**
100654

**programs_offered_cip:**
1.0901
1.1001
1.9999
3.0599
4.0301
9.0199
10.0202
11.0101
13.0101
13.0401
13.1001
13.1012
13.1202
13.1205
13.121
13.1314
14.0801
14.1001
14.1901
14.9999
15.0399
15.0899
15.1001
19.0101
23.0101
24.0102
26.0101
27.0101
31.0505
40.0501
40.0801
40.0899
42.0101
42.2803
43.0103
44.0701
45.1001
45.1101
50.0701
50.0901
51.0203
52.0201
52.0203
52.0301
52.0801
52.1401

**Comment by maneshkommidi** [comment]
@saintsoup52  In **IPEDS_CIP_LIST_20180518_lite.xlsx** file, I observed we have data only in 3 columns, can we remove the other columns where we do not have any data.

**Comment by saintsoup52** [comment]
@maneshkommidi Normally we try to keep the file in the same format as we download from ED. In this case that ED file is 41 mb which causes its own problems, especially when it comes to VA computers. So I think it makes sense to only keep the three columns.

**Comment by briangryth** [comment]
@saneshark and @jkassemi - do we have an example of one or two schools that have a STEM program? @jbalboni is looking to validate the front end and I can't seem to find a specific school

**Comment by saintsoup52** [comment]
Why don't you try LOS ANGELES TRADE TECHNICAL COLLEGE

I know from College Scorecard that they have a science program... Scorecard uses the same basic formula for looking for STEM schools we plan to use.

https://www.vets.gov/gi-bill-comparison-tool/profile/14931405

https://collegescorecard.ed.gov/school/?117724-Los-Angeles-Trade-Technical-College

**Comment by saneshark** [comment]
Code has been merged to staging and production! 🍻 🍾 🎉
