### ISSUE TITLE
Update the WEAMS import logic to accommodate the new columns 

### ISSUE THREAD

**Issue by briangryth** [department-of-veterans-affairs/gibct-data-service#337]
issue to update the import logic to support importing the additional fields, including sample seeds file, and specs, serializer changes and specs.

**Comment by saneshark** [comment]
The migrations have been merged to staging and production and they have been run. Now all that remains is building the institutions table with the new data file.

@saintsoup52 just a heads up, once we make this change, any new weams file must include the 4 new columns or you will encounter errors. There is no way to make uploads reverse compatible. That being said, the columns could be null for the time being, there just might be side-effects on the FE with respect to how null is to be handled. cc: @rianfowler @jkassemi

**Comment by saintsoup52** [comment]
Thank you for the heads up... I will try to remind our friends at EDU that they need to add the columns in the current WEAMS file they are uploading if they are not there already.

**Comment by jholton** [comment]
per comments above, this was completed.
re: #340
