### ISSUE TITLE
Integrate strong migrations gem

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/gibct-data-service#345]
To automatically catch potential unsafe migrations, we should integrate the strong migrations gem that's already in place on vets-api (https://github.com/ankane/strong_migrations)

**Comment by zurbergram** [comment]
This was added and deployed to production in https://github.com/department-of-veterans-affairs/gibct-data-service/releases/tag/gi-bill-data-service/v0.0.91

**Comment by jholton** [comment]
re: #387
