### ISSUE TITLE
WEAMS Failed Upload

### ISSUE THREAD

**Issue by jmcneal65** [department-of-veterans-affairs/gibct-data-service#353]
There are possibly two problems with the file you are uploading to WEAMS:
•	Wrong Order – The “accredited” field has moved from one place to another. I don’t think this is the issue, but it should be easy enough to check it by moving it into the right place and trying to upload it.
•	New fields – This new WEAMS file has a number of new fields that were not in the previous versions uploaded. If I had to guess those new fields are causing the error. This can be easily checked by just deleting those columns and trying to upload the file
![ds weams data error message](https://user-images.githubusercontent.com/26603766/44724849-713d7d80-aac3-11e8-89db-41b7a314a723.png)

**Comment by jholton** [comment]
Fixed by #355
