### ISSUE TITLE
Outline usage process for stakeholder staging.

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/gibct-data-service#44]
Outline the process in which stakeholders can try out the application until we are able to deploy the application to production.

**Comment by jeffmaher** [comment]
@plusjeff is aiming for completion on 4/11

**Comment by jeffmaher** [comment]
@rickleegit :  I'll get this to you late today or very early tomorrow, then will hand over to you for review.

**Comment by jeffmaher** [comment]
PR: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/117

**Comment by jeffmaher** [comment]
Sent for review by @rickleegit ... can close this ticket following review (PR in vets.gov-team repo)

**Comment by rickleegit** [comment]
reviewed, merged and closed. Thanks!
