### ISSUE TITLE
Get VA Network Only URL

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/gibct-data-service#46]
Work with the NSOC to get a VA only URL, so that only VA employees on the network can get to the application.

**Comment by jeffmaher** [comment]
@ShawnArnwine is finding possible options and working with VA NSOC:
- Have VA NSOC provide a URL to only allow VA network traffic in
- Have a public URL (still requiring username/password), but make sure this jives with our ATO

**Comment by rickleegit** [comment]
@plusjeff; I believe this is no longer an issue? Can we close?

**Comment by jeffmaher** [comment]
Correct! This can be closed.

**Comment by saintsoup52** [comment]
Will this mean I will still have access to the data service? That would be a relief.
