### ISSUE TITLE
Get list of users for GIDS

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/gibct-data-service#49]
A list of e-mail addresses for users of the GIBCT Data Service

**Comment by rickleegit** [comment]
Stephanie Price Stephanie.Price3@va.gov
Eddie Ricks Eddie.Ricks@va.gov
Shay Norton Shay.Norton@va.gov
Jude Lopez Jude.Lopez1@va.gov

**Comment by jeffmaher** [comment]
Added: Patrick Campbell Patrick.Campbell@cfpb.gov
