### ISSUE TITLE
DS fails to build data.csv on Staging

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gibct-data-service#62]
To duplicate:
1. Go to the dashboard (menu item "dashboard")
2. If all CSVs are loaded (you'll see a file name next to every csv type) the red "Build Data.csv" button will appear in the top left corner. If not, you'll need to load in the missing CSVs using the upload link next to the missing CSV slot.
3. Once the "Build Data.csv" button is visible, click it to produce the error.

**Comment by jeffmaher** [comment]
@mphprogrammer What is the expected behavior if the error message didn't occur.

**Comment by mphprogrammer** [comment]
You would be returned to the same dashboard page with a bluish success message appearing below the menubar (something like "data.csv successfully created")
