### ISSUE TITLE
Had trouble uploading CSV file

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#63]
I was trying to upload the new WEAMS csv file and it was not coming up as option to select when I choose a file.

Looks like I needed to switch the file type on the bottom right of the upload screen from "custom files" to "all files". This confused me for about 30 minutes and I know will confuse others.

Is there a way to default to all files or show txt or csv files?

![image](https://cloud.githubusercontent.com/assets/4397508/15010811/2f358c90-11bc-11e6-96ce-ec31b9e1c29a.png)

Here is what I am seeing when I go that same folder in the data service
![image](https://cloud.githubusercontent.com/assets/4397508/15010872/8c1e23b8-11bc-11e6-8399-b61eb1fe4302.png)

**Comment by mphprogrammer** [comment]
This may be an IE issue - on MACs they seem to come up as *.csv.

**Comment by saintsoup52** [comment]
I am using Chrome... it is not impossible to deal with now that I know the problem., just a little annoying when I am doing lots of file updates.

**Comment by rickleegit** [comment]
@mphprogrammer: Status? Can we close?

**Comment by mphprogrammer** [comment]
I think so ... but out of curiosity did this happen for you too?

**Comment by saintsoup52** [comment]
This is still an issue... but this is definitely in the category of like to have.

**Comment by rickleegit** [comment]
i have not had an issue, but Mac.
