### ISSUE TITLE
After uploading WEAMS file it went to blank screen

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#64]
Sorry... I didn't mean to break it.

I uploaded the new WEAMS file and it went a blank screen. When I relogged in, did not appear that the WEAMS file had in fact be uploaded.

**Comment by saintsoup52** [comment]
It happened again... I was taken to the link below and met with a completely white screen.

http://dsva-vetsgov-staging-gids-1553687019.us-east-1.elb.amazonaws.com/csv_files

**Comment by mphprogrammer** [comment]
Fixed - was a time out issue on the ELB.

**Comment by mphprogrammer** [comment]
ELB Timeout issue, fixed.

**Comment by saintsoup52** [comment]
I was able to download the whole file in record time today!!
