### ISSUE TITLE
Sort list of uploaded csv files

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#66]
Is it possible to sort the list of uploaded CSV files?

I was trying to see when different WEAMS files were uploaded but I had to read through every single file name to see. 

might be helpful to be able to sort by date and CSV file type.

**Comment by saintsoup52** [comment]
Now that the download button is on the dashboard page this is not nearly as much an issue... would be nice because at some point the list of uploads will be VERY VERY long, but definitely not a necessity.

**Comment by rickleegit** [comment]
Closing
