### ISSUE TITLE
Export Order

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#69]
It appears the export feature reorders the columns. For example, in the 7th column of the export the data is "va_highest_degree_offered" and in the current file that does not appear till column AF.

Reordering the data will mess up the data dashboards. 

is it possible to get the column headers to export in this order:
facility_code
institution
city
state
zip
country
type
correspondence
flight
bah
cross
ope
insturl
vet_tuition_policy_url
pred_degree_awarded
locale
gibill
undergrad_enrollment
yr
student_veteran
student_veteran_link
poe
eight_keys
dodmou
sec_702
vetsuccess_name
vetsuccess_email
credit_for_mil_training
vet_poc
student_vet_grp_ipeds
soc_member
va_highest_degree_offered
retention_rate_veteran_ba
retention_all_students_ba
retention_rate_veteran_otb
retention_all_students_otb
persistance_rate_veteran_ba
persistance_rate_veteran_otb
graduation_rate_veteran
graduation_rate_all_students
transfer_out_rate_veteran
transfer_out_rate_all_students
salary_all_students
repayment_rate_all_students
avg_stu_loan_debt
calendar
tuition_in_state
tuition_out_of_state
books
online_all
p911_tuition_fees
p911_recipients
p911_yellow_ribbon
p911_yr_recipients
accredited
accreditation_type
accreditation_status
caution_flag
caution_flag_reason
complaints_facility_code
complaints_financial_by_fac_code
complaints_quality_by_fac_code
complaints_refund_by_fac_code
complaints_marketing_by_fac_code
complaints_accreditation_by_fac_code
complaints_degree_requirements_by_fac_code
complaints_student_loans_by_fac_code
complaints_grades_by_fac_code
complaints_credit_transfer_by_fac_code
complaints_job_by_fac_code
complaints_transcript_by_fac_code
complaints_other_by_fac_code
complaints_main_campus_roll_up
complaints_financial_by_ope_id_do_not_sum
complaints_quality_by_ope_id_do_not_sum
complaints_refund_by_ope_id_do_not_sum
complaints_marketing_by_ope_id_do_not_sum
complaints_accreditation_by_ope_id_do_not_sum
complaints_degree_requirements_by_ope_id_do_not_sum
complaints_student_loans_by_ope_id_do_not_sum
complaints_grades_by_ope_id_do_not_sum
complaints_credit_transfer_by_ope_id_do_not_sum
complaints_jobs_by_ope_id_do_not_sum
complaints_transcript_by_ope_id_do_not_sum
complaints_other_by_ope_id_do_not_sum

**Comment by saintsoup52** [comment]
This is still an issue for me... sorry this is a essential step for us to use this data in the data dashboards.

**Comment by saintsoup52** [comment]
Sorry... I can't test the data in this order, plus we can't use with the data dashboards until it is put back in the correct order.

**Comment by mphprogrammer** [comment]
Looking into this.

**Comment by saintsoup52** [comment]
Sorry guys EDU can't transition off my database till we get this resolved... this breaks the data dashboards which must also but updated every time a new data update is pushed to the CT.

**Comment by mphprogrammer** [comment]
Merged and waiting for deploy.
