### ISSUE TITLE
Uploading complaint file ERROR

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#72]
When i tried to upload the complaint file I got an error because it could not recognize the headers.

Turns out it was looking for the headers on the 8th row.

Is it possible for it to look for the headers first row and then if can't find them then the 8th row?

I am worried the complaint file report might change in the future and it is not intuitive to have the headers on the 8th row.

![image](https://cloud.githubusercontent.com/assets/4397508/15355767/c0066918-1cc2-11e6-880f-df695dc44c19.png)

**Comment by rickleegit** [comment]
@mphprogrammer: Status? Can we close?

**Comment by rickleegit** [comment]
Duplicate.
