### ISSUE TITLE
Add "download" button to dashboard

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#73]
It is hard to find the latest version of a file to download.

The current path is click on the "CSV files" tab and then find the latest version in a long, long list.

Can we add a "download" column to the dashboard page?

![image](https://cloud.githubusercontent.com/assets/4397508/15355809/09f2dfb6-1cc3-11e6-858b-08882da71764.png)

**Comment by mphprogrammer** [comment]
Done and merged waiting for deploy.

**Comment by saintsoup52** [comment]
This is awesome!! thank you.

**Comment by mphprogrammer** [comment]
Closing
