### ISSUE TITLE
Travis CI fails when requiring multiple databases for testing.

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/gibct-data-service#75]
GIBCT Data service merge is failing during Travis CI because it requires an additional db:create and migration for the GIBCT database. Rspec cannot run, and fails as a result. We may need to add a GIBCT submodule to the DS repo.

**Comment by mphprogrammer** [comment]
As a side note, rspec is 100% when testing locally.

**Comment by ayaleloehr** [comment]
Resolved with: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/80/commits/9ebc2414f07a75f462fb1f122c92bd72341fe798
