### ISSUE TITLE
Strips "#" from school names

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#76]
The VA school list has over 155 school with a "#" in the name. The data service strips those symbols from the school names.

We need to keep those special characters. For example:

"#1 CYCLE CENTER H D INC" vs. "1 CYCLE CENTER H D INC"
"ATLANTA FIRE DEPARTMENT STATION #32" vs. "ATLANTA FIRE DEPARTMENT STATION 32"

**Comment by mphprogrammer** [comment]
On it.

**Comment by mphprogrammer** [comment]
Handled by latest merge.

**Comment by saintsoup52** [comment]
This issue is still happening with apostrophes and ampersands... can we just stop it from removing special characters?
