### ISSUE TITLE
Quotations around OPE ID

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#84]
Is it possible to add the quotations back around the OPE ID when we create the export csv file?

When I put the file into the databoard I loose the leading "0"'s and this messes up a lot of calculations.

**Comment by rickleegit** [comment]
Will be fixed with https://github.com/department-of-veterans-affairs/gibct-data-service/issues/69

Just OPE.

**Comment by saintsoup52** [comment]
This does not appear to be fixed... Sorry guys.

**Comment by mphprogrammer** [comment]
Haven't fixed that yet.

**Comment by mphprogrammer** [comment]
This is a "large lift" as enclosing quotes in a CSV export is not easy, and will cause a format error in rails.

**Comment by saintsoup52** [comment]
Is the problem quotes themselves or any special character?

We could use another special character like parathenthesis or dashes to substitute.

**Comment by saintsoup52** [comment]
I think that works for me!

**Comment by saintsoup52** [comment]
Then let's use "(" and ")" on either side... I just need the special characters to hold the zeros when it converts to excel.
