### ISSUE TITLE
Links to Student Veterans Groups

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#85]
It looks like the data service is missing one of the filters I use when displaying links student veterans groups.

If the URL is just to the SVA page I filter it out. 
Max(IIf([Website]="http://www.studentveterans.org","",[Website]))

However, I think there are some schools with multiple IPEDS entries one with a SVA link and one without... so we need to just weed out the SVA URLs.

Unfortunately a substantial number of the group links just go back to the SVA homepage and not the individual chapter pages. I have been trying to get SVA to standardize their URL structure so we could send directly to their directory but they just don't have the appetite.

**Comment by mphprogrammer** [comment]
OK - I'll get on this now.

**Comment by mphprogrammer** [comment]
Completed - waiting for deploy to staging
