### ISSUE TITLE
Schools with "$0" in tuition

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#86]
There are a number of schools that do not charge tuition (e.g., AF Academy) but are showing up as blank in the data service.

If the IPEDS data says "$0" it should stay in the data.

Here is a real world example: VINAL TECHNICAL HIGH SCHOOL IPEDS #441335)

**Comment by mphprogrammer** [comment]
That would be in the ipeds ic ay csv? tuition in state and out of state?

**Comment by mphprogrammer** [comment]
Which CSV in specific are we talking about?

**Comment by mphprogrammer** [comment]
If its the ipeds ic py csv, I get '.'s for that entry in the CSV
![screen shot 2016-05-27 at 1 23 16 pm](https://cloud.githubusercontent.com/assets/4104431/15615940/fe70ee32-240e-11e6-8e71-c40303b8937c.png)
 --

**Comment by saintsoup52** [comment]
We can ignore the periods... But for 32 schools in either the py or ay files have a 0 for average tuition.

**Comment by ben-USDS-damman** [comment]
@mphprogrammer @saintsoup52 Looks like this is still an issue. Do I understand correctly that for some schools we receive zero values but we convert them to null values?

**Comment by saintsoup52** [comment]
That is correct... most come to us as NULL (or with a ".") and should stay NULL, but a few are truly $0 and should stay $0 in the data.

**Comment by mphprogrammer** [comment]
Yeah - I convert 'NULL' and '.' to nil when reading the CSVs. 0 is a value in its own right.

**Comment by mphprogrammer** [comment]
We can safely close this issue.
