### ISSUE TITLE
Accreditation Type (Region, National, Hyrbid)

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#87]
The data services has over 1,000 more accreditation types in the data file then I show in the database.

For example accreditation type is "Regional", "National" or "Hybrid".

 I don't know why this is the case... but I wanted to flag it.

Does it have to do with using both the IPEDS and OPE in the crosswalk?

**Comment by mphprogrammer** [comment]
This is the map I use:
`ACCREDITATIONS = {
    "regional" => ["middle", "new england", "north central", "southern", "western"],
    "national" => ["career schools", "continuing education", "independent colleges", 
      "biblical", "occupational", "distance", "new york", "transnational"],
    "hybrid" => ["acupuncture", "nursing", "health education", "liberal","legal", 
      "funeral", "osteopathic", "pediatric", "theological", "massage", "radiologic", 
      "midwifery", "montessori", "career arts", "design", "dance", "music", 
      "theatre", "chiropractic"]
  }`

I do a match for the terms between [ and ] in the agency name to derive the accreditation type. I'll try to do a hand count of each accreditation type ...

**Comment by mphprogrammer** [comment]
There is also "northwest ..." with about ~140 records do we use that in regional?

**Comment by mphprogrammer** [comment]
Checking in Excel
17302 Regional

**Comment by saintsoup52** [comment]
The accreditation file is a tough one to get right... This might be on my end, who knows.

First we need to make sure we are using the right filters. Below are the initial filter criteria:
-  "Periods" contains the word "current"
- "Accreditation_Type" = "Institutional"
  We ignore everything else.

The second step is assigning the correct IPEDS IDs... there are two IPEDS IDs to look at. First we look to see if there is a "Campus_IPEDS_UnitID", if yes then we use that ID, and if not we use the "Institution_IPEDS_UnitID."

Schools may have multiple institutional accreditors assigned to a single IPEDS ID. So the third step is if we find the magic words  in one of the accreditor's names (e.g., "new england") then we say that school has "regional accreditation". if has one of the magic words from the second list then it is "hybrid" accreditation and if none of the words are found then it has "national" accreditation.

I am going to find some specific examples where our list is different and see if I can diagnosis this issue.

**Comment by saintsoup52** [comment]
Well this one has me perplexed... but the good news is that the data service seems to be doing this right and my database is missing some of them.

I can't seem to detect a pattern why my database is missing the ones the data service is picking up... but hey... don't look a gift horse in the mouth!
