### ISSUE TITLE
Data CSV Request

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gibct-data-service#89]
@saintsoup52 , 

We are in need of the latest complaints, weams, and crosswalk files that you have. @mphprogrammer is attempting to diagnose the complaints issue but needs to ensure that there are not data discrepancies at the source first. 

Can you simply attach those files to this issue?

Thanks,

Rick

cc: @ayaleloehr

**Comment by saintsoup52** [comment]
All of the most current files should be uploaded to the data service... and unfortunately I cannot just post the complaints or WEAMS file to this github thread.

**Comment by rickleegit** [comment]
because rick forgot something.
