### ISSUE TITLE
Row with column header changes

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#90]
So this is the second time this has been an issue for me... the original data source has changed the header format moving up or down the row with the column headers.

The latest was HCM... in the file you had the headers started on row 3, in the most recent file they start on row 4.

Is it possible to look at the row as you program and if it doesn't find it start again at row 1 and work its way down to row 10 or so?

I worry that these weird headers will go up and down without use knowing about it.

It was nice to be able to diagnose the problem by downloading the last working file!! #score!

**Comment by rickleegit** [comment]
Add to data dictionary and training doc.
