### ISSUE TITLE
Coorespondence & Flight

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#95]
Tagging too many schools as flight or correspondence.

Below is the test... if a school is an IHL or NCD then they are not labelled as flight or correspondence.

IIf([Institution of Higher Learning Indicator]="No" And [OJT Indicator]="No" And [Correspondence Indicator]="No" And [Flight Indicator]="Yes" And [Non-College Degree Indicator     ]="No","Yes",Null) AS flight, 

IIf([Institution of Higher Learning Indicator]="No" And [OJT Indicator]="No" And [Correspondence Indicator]="Yes" And [Flight Indicator]="No" And [Non-College Degree Indicator     ]="No","Yes",Null) AS correspondence,

**Comment by rickleegit** [comment]
<img width="553" alt="screen shot 2016-05-27 at 4 45 24 pm" src="https://cloud.githubusercontent.com/assets/11138830/15620798/83ed1b1a-242a-11e6-9785-c2600a21f027.png">

**Comment by mphprogrammer** [comment]
@saintsoup52 I've been using the 2nd digit of the facility code as the ojt flag - I assume I should switch that to the ojt_indicator.

**Comment by saintsoup52** [comment]
yes... the second digit of the facility code should be the determining factor for OJT status (not WEAMS).
